site_name: Codesavoir Knowledge Base
site_description: Professional DevOps & IT engineering knowledge hub
site_url: https://knowledge.codesavoir.com
repo_url: https://github.com/codesavoir/knowledge
repo_name: GitHub
copyright: "©2025 Codesavoir"

nav:
  - Home: index.md
  - Cloud Computing:
      - Introduction: cloud-computing/overview.md
      - Service Models (IaaS / PaaS / SaaS): cloud-computing/service-models.md
      - Deployment Models: cloud-computing/deployment-models.md
      - Key Concepts (Regions, Zones): cloud-computing/key-concepts.md
      - Virtualization & Containers: cloud-computing/virtualization-containers.md
      - Compute, Storage & Networking Basics: cloud-computing/compute-storage-networking.md
      - Scalability & Elasticity: cloud-computing/scalability-elasticity.md
      - Security Basics: cloud-computing/security-basics.md
      - Cost & Pricing: cloud-computing/cost-pricing.md
      - Case Studies & Examples: cloud-computing/case-studies.md
  - Git Flow:
      - Introduction: git-flow/overview.md
      - Git Basics: git-flow/git-basics.md
      - Branching Strategy: git-flow/branching-strategy.md
      - Atomic Commits: git-flow/atomic-commits.md
      - Commit Messages: git-flow/commit-messages.md
      - Pull Requests (PRs): git-flow/pull-requests.md
      - Issues & Tracking: git-flow/issues-tracking.md
      - DevOps Mindset & Collaboration: git-flow/devops-mindset.md
      - CI Integration: git-flow/ci-integration.md
      - Release Management: git-flow/release-management.md
      - Common Mistakes & Fixes: git-flow/common-mistakes.md
      - Cheat Sheet: git-flow/cheat-sheet.md

# Theme configuration
theme:
  name: material
  language: en
  custom_dir: overrides
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - toc.follow
    - tags
    - navigation.tracking
    - navigation.indexes
    - navigation.path
    - search.share

  icon:
     logo: fontawesome/brands/github

# Plugins
plugins:
  - search
  - tags
  - timetoread:
      wpm: 240
      allPages: True
      textColour: ffffff
  - minify:
      minify_html: true
  - glightbox
  - macros
  - awesome-pages
  - redirects
  - mkdocs-simple-hooks
  - mkdocs-video
  - glightbox   # Lightbox for images
  - git-revision-date-localized:
      enable_creation_date: true
      locale: en
      fallback_to_build_date: false
      enable_git_follow: true
      enabled: true
      strict: true
      type: timeago
      custom_format: "%d. %B %Y"
      timezone: Europe/Paris
      exclude:
        - index.md
  - git-authors:
      authorship_threshold_percent: 0
      enabled_on_serve: true
      exclude:
        - index.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      linenums: false
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - attr_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

site_author: Codesavoir Team
edit_uri: edit/main/docs/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/codesavoir
  tags:
    DevOps: DevOps Practices
    SRE: Site Reliability Engineering
    Cloud: Cloud
  analytics:
    provider: google
    property: G-XXXXXXX
  consent:
    title: Cookie consent
    description: >-
      We use cookies to analyze traffic and improve the experience.
  generator: false

extra_css:
  - assets/styles/overrides.css
extra_javascript:
  - assets/js/extra.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - assets/js/mermaid-init.js
